# Generated by Django 4.2.5 on 2023-10-15 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quora', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_id',
            new_name='user',
        ),
    ]
