# Generated by Django 4.2.5 on 2023-10-16 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quora', '0005_message_space_msg_image_message_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='msg_image',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='space',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
