# Generated by Django 4.2.5 on 2023-10-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quora', '0009_alter_profile_avatar_alter_profile_end_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.CharField(help_text='enter the question you want to ask', max_length=250),
        ),
    ]
